import 'package:flutter/material.dart';

class SportType {
  final String id;
  final String name;
  final IconData icon;
  final Color color;

  const SportType({
    required this.id,
    required this.name,
    required this.icon,
    required this.color,
  });

  static const List<SportType> all = [
    SportType(id: 'adventure_racing', name: 'Adventure Racing', icon: Icons.explore, color: Colors.red),
    SportType(id: 'aerobics', name: 'Aerobics', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'alpine_skiing', name: 'Alpine Skiing / Downhill Skiing', icon: Icons.downhill_skiing, color: Colors.teal),
    SportType(id: 'american_football', name: 'American Football', icon: Icons.sports_football, color: Colors.indigo),
    SportType(id: 'aquathlon', name: 'Aquathlon', icon: Icons.pool, color: Colors.blue),
    SportType(id: 'badminton', name: 'Badminton', icon: Icons.sports_tennis, color: Colors.indigo),
    SportType(id: 'ball_games', name: 'Ball Games', icon: Icons.sports_basketball, color: Colors.indigo),
    SportType(id: 'baseball', name: 'Baseball', icon: Icons.sports_baseball, color: Colors.indigo),
    SportType(id: 'basketball', name: 'Basketball', icon: Icons.sports_basketball, color: Colors.indigo),
    SportType(id: 'bowling', name: 'Bowling', icon: Icons.videogame_asset, color: Colors.indigo),
    SportType(id: 'boxing', name: 'Boxing', icon: Icons.sports_mma, color: Colors.red),
    SportType(id: 'canoeing', name: 'Canoeing', icon: Icons.kayaking, color: Colors.blue),
    SportType(id: 'cheerleading', name: 'Cheerleading', icon: Icons.emoji_events, color: Colors.purple),
    SportType(id: 'circuit_training', name: 'Circuit Training', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'climbing', name: 'Climbing', icon: Icons.terrain, color: Colors.green),
    SportType(id: 'combat_sport', name: 'Combat Sport / Martial Arts', icon: Icons.sports_mma, color: Colors.red),
    SportType(id: 'cricket', name: 'Cricket', icon: Icons.sports_cricket, color: Colors.indigo),
    SportType(id: 'cross_country_skiing', name: 'Cross Country Skiing / Nordic Skiing', icon: Icons.downhill_skiing, color: Colors.teal),
    SportType(id: 'crossfit', name: 'Crossfit', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'crosstrainer', name: 'Crosstrainer (Elliptical)', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'cycling', name: 'Cycling', icon: Icons.directions_bike, color: Colors.cyan),
    SportType(id: 'dancing', name: 'Dancing', icon: Icons.music_note, color: Colors.purple),
    SportType(id: 'duathlon', name: 'Duathlon', icon: Icons.directions_run, color: Colors.red),
    SportType(id: 'fishing', name: 'Fishing', icon: Icons.phishing, color: Colors.blueGrey),
    SportType(id: 'fitness_class', name: 'Fitness Class', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'floorball', name: 'Floorball', icon: Icons.sports_hockey, color: Colors.indigo),
    SportType(id: 'freediving', name: 'Freediving', icon: Icons.scuba_diving, color: Colors.blue),
    SportType(id: 'frisbee_golf', name: 'Frisbee Golf / Frisbee', icon: Icons.adjust, color: Colors.indigo),
    SportType(id: 'futsal', name: 'Futsal', icon: Icons.sports_soccer, color: Colors.indigo),
    SportType(id: 'golf', name: 'Golf', icon: Icons.sports_golf, color: Colors.indigo),
    SportType(id: 'gym', name: 'Gym', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'gymnastics', name: 'Gymnastics', icon: Icons.accessibility_new, color: Colors.purple),
    SportType(id: 'handball', name: 'Handball', icon: Icons.sports_handball, color: Colors.indigo),
    SportType(id: 'hiking', name: 'Hiking', icon: Icons.hiking, color: Colors.green),
    SportType(id: 'horseback_riding', name: 'Horseback Riding', icon: Icons.pets, color: Colors.green),
    SportType(id: 'hunting', name: 'Hunting', icon: Icons.adjust, color: Colors.green),
    SportType(id: 'ice_hockey', name: 'Ice Hockey', icon: Icons.sports_hockey, color: Colors.indigo),
    SportType(id: 'ice_skating', name: 'Ice Skating', icon: Icons.ice_skating, color: Colors.teal),
    SportType(id: 'indoor', name: 'Indoor', icon: Icons.home, color: Colors.grey),
    SportType(id: 'indoor_cycling', name: 'Indoor Cycling', icon: Icons.directions_bike, color: Colors.cyan),
    SportType(id: 'indoor_rowing', name: 'Indoor Rowing', icon: Icons.rowing, color: Colors.blue),
    SportType(id: 'kayaking', name: 'Kayaking', icon: Icons.kayaking, color: Colors.blue),
    SportType(id: 'kettlebell', name: 'Kettlebell', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'kitesurfing', name: 'Kitesurfing / Kiting', icon: Icons.surfing, color: Colors.blue),
    SportType(id: 'motorsports', name: 'Motorsports', icon: Icons.directions_car, color: Colors.red),
    SportType(id: 'mountain_biking', name: 'Mountain Biking', icon: Icons.directions_bike, color: Colors.cyan),
    SportType(id: 'mountaineering', name: 'Mountaineering', icon: Icons.terrain, color: Colors.green),
    SportType(id: 'multisport', name: 'Multisport', icon: Icons.sports, color: Colors.red),
    SportType(id: 'nordic_walking', name: 'Nordic Walking', icon: Icons.directions_walk, color: Colors.green),
    SportType(id: 'obstacle_racing', name: 'Obstacle Racing', icon: Icons.run_circle, color: Colors.red),
    SportType(id: 'openwater_swimming', name: 'Openwater Swimming', icon: Icons.pool, color: Colors.blue),
    SportType(id: 'orienteering', name: 'Orienteering', icon: Icons.explore, color: Colors.green),
    SportType(id: 'outdoor_gym', name: 'Outdoor Gym', icon: Icons.fitness_center, color: Colors.purple),
    SportType(id: 'paddling', name: 'Paddling', icon: Icons.kayaking, color: Colors.blue),
    SportType(id: 'paragliding', name: 'Paragliding', icon: Icons.air, color: Colors.blue),
    SportType(id: 'parkour', name: 'Parkour', icon: Icons.run_circle, color: Colors.red),
    SportType(id: 'racquetball', name: 'Racquetball', icon: Icons.sports_tennis, color: Colors.indigo),
    SportType(id: 'roller_skating', name: 'Roller Skating', icon: Icons.ice_skating, color: Colors.teal),
    SportType(id: 'roller_skiing', name: 'Roller Skiing', icon: Icons.downhill_skiing, color: Colors.teal),
    SportType(id: 'rowing', name: 'Rowing', icon: Icons.rowing, color: Colors.blue),
    SportType(id: 'rugby', name: 'Rugby', icon: Icons.sports_rugby, color: Colors.indigo),
    SportType(id: 'running', name: 'Running', icon: Icons.directions_run, color: Colors.orange),
    SportType(id: 'sailing', name: 'Sailing', icon: Icons.sailing, color: Colors.blue),
    SportType(id: 'scuba_diving', name: 'Scuba Diving', icon: Icons.scuba_diving, color: Colors.blue),
    SportType(id: 'skateboarding', name: 'Skateboarding', icon: Icons.skateboarding, color: Colors.red),
    SportType(id: 'ski_touring', name: 'Ski Touring', icon: Icons.downhill_skiing, color: Colors.teal),
    SportType(id: 'snorkeling', name: 'Snorkeling', icon: Icons.scuba_diving, color: Colors.blue),
    SportType(id: 'snowshoeing', name: 'Snowshoeing', icon: Icons.snowshoeing, color: Colors.teal),
    SportType(id: 'snowboarding', name: 'Snowboarding', icon: Icons.snowboarding, color: Colors.teal),
    SportType(id: 'soccer', name: 'Soccer / Football', icon: Icons.sports_soccer, color: Colors.indigo),
    SportType(id: 'softball', name: 'Softball', icon: Icons.sports_baseball, color: Colors.indigo),
    SportType(id: 'squash', name: 'Squash', icon: Icons.sports_tennis, color: Colors.indigo),
    SportType(id: 'standup_paddling', name: 'Standup Paddling', icon: Icons.kayaking, color: Colors.blue),
    SportType(id: 'stretching', name: 'Stretching', icon: Icons.accessibility_new, color: Colors.purple),
    SportType(id: 'surfing', name: 'Surfing', icon: Icons.surfing, color: Colors.blue),
    SportType(id: 'swimming', name: 'Swimming', icon: Icons.pool, color: Colors.blue),
    SportType(id: 'swimrun', name: 'Swimrun', icon: Icons.pool, color: Colors.blue),
    SportType(id: 'table_tennis', name: 'Table Tennis', icon: Icons.sports_tennis, color: Colors.indigo),
    SportType(id: 'telemark_skiing', name: 'Telemark Skiing', icon: Icons.downhill_skiing, color: Colors.teal),
    SportType(id: 'tennis', name: 'Tennis (including Padel)', icon: Icons.sports_tennis, color: Colors.indigo),
    SportType(id: 'track_and_field', name: 'Track and Field', icon: Icons.run_circle, color: Colors.orange),
    SportType(id: 'trail_running', name: 'Trail Running', icon: Icons.directions_run, color: Colors.orange),
    SportType(id: 'treadmill', name: 'Treadmill', icon: Icons.directions_run, color: Colors.orange),
    SportType(id: 'trekking', name: 'Trekking', icon: Icons.hiking, color: Colors.green),
    SportType(id: 'triathlon', name: 'Triathlon', icon: Icons.sports, color: Colors.red),
    SportType(id: 'volleyball', name: 'Volleyball', icon: Icons.sports_volleyball, color: Colors.indigo),
    SportType(id: 'walking', name: 'Walking', icon: Icons.directions_walk, color: Colors.green),
    SportType(id: 'water_sports', name: 'Water Sports', icon: Icons.pool, color: Colors.blue),
    SportType(id: 'windsurfing', name: 'Windsurfing', icon: Icons.surfing, color: Colors.blue),
    SportType(id: 'yoga', name: 'Yoga', icon: Icons.accessibility_new, color: Colors.purple),
    SportType(id: 'other_1', name: 'Other 1', icon: Icons.more_horiz, color: Colors.grey),
    SportType(id: 'other_2', name: 'Other 2', icon: Icons.more_horiz, color: Colors.grey),
    SportType(id: 'other_3', name: 'Other 3', icon: Icons.more_horiz, color: Colors.grey),
    SportType(id: 'other_4', name: 'Other 4', icon: Icons.more_horiz, color: Colors.grey),
    SportType(id: 'other_5', name: 'Other 5', icon: Icons.more_horiz, color: Colors.grey),
    SportType(id: 'other_6', name: 'Other 6', icon: Icons.more_horiz, color: Colors.grey),
  ];

  static SportType fromId(String id) {
    return all.firstWhere((s) => s.id == id, orElse: () => all.firstWhere((s) => s.id == 'other_1'));
  }
}
